// Generated by CoffeeScript 1.6.3
(function() {
  var handleMessage;

  handleMessage = function(msg) {
    if (msg.name === 'link') {
      return safari.extension.popovers[0].contentWindow.addLink(msg.message);
    }
  };

  safari.application.addEventListener("message", handleMessage, false);

}).call(this);
